steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/lexia-aoc-2602-2/cloud-run-source-deploy/webhook-node:v2.0', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'southamerica-east1-docker.pkg.dev/lexia-aoc-2602-2/cloud-run-source-deploy/webhook-node:v2.0']
images:
- 'southamerica-east1-docker.pkg.dev/lexia-aoc-2602-2/cloud-run-source-deploy/webhook-node:v2.0'
